[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "SOGo"
description = "SOGo 6 backend API server"
authors = [
    {name = "Quentin Hivert", email = "quentin.hivert.fr@gmail.com"},
]
license = { text = "GPL-3.0-or-later" }
readme = "README.md"
dynamic = [ "version" ]
requires-python = ">=3.13,<4.0"
keywords = ["sogo", "webmail", "mail", "calendar"]
dependencies = [
    "webauthn>=1.9.0",
    "bcrypt",
    "celery",
    "click",
    "cryptography",
    "defusedxml",
    "flask",
    "flask-compress",
    "flask-cors",
    "flask-smorest",
    "gunicorn",
    "icalendar",
    "marshmallow",
    "mysql-connector-python",
    "psycopg",
    "pydantic",
    "pydantic-settings",
    "pyjwt",
    "python-ldap",
    "pysaml2>=7.4",
    "pytest-mock",
    "redis",
    "sievelib",
    "types-smorest",
    "webauthn",
    "yarl",
]


[tool.poetry]
version = "6.0.0-alpha1"  # base version
packages = [
    { include = "app" },
]
exclude = ["tests"]

[tool.poetry.group.dev.dependencies]
pytest = "^9.0.0"
pytest-cov = "^7.0.0"
black = "^26.1"
pylint = "^4.0.0"
pre-commit = "^4.2.0"
mypy = "^1.17.1"


[tool.poetry.requires-plugins]
poetry-plugin-export = ">=1.8"

[tool.poetry.scripts]
# poetry run start
start = "app.run:main"
# poetry run agent
agent = "app.agent.run:main"
# poetry run agent-beat
agent-beat = "app.agent.run:beat"


[tool.pytest.ini_options]
testpaths = [
    "tests"
]


[tool.pylint.basic]
module-naming-style="any"
class-naming-style="PascalCase"
method-naming-style="snake_case"
attr-naming-style="snake_case"
function-naming-style="snake_case"
variable-naming-style="snake_case"
argument-naming-style="snake_case"
disable= [
    "missing-module-docstring",
    "too-few-public-methods",
    "pointless-string-statement",
    "too-many-arguments",
    "too-many-positional-arguments",
    "unused-argument"
]
max-line-length=240
ignored-modules=["psycopg", "ldap"]

[tool.mypy]
disallow_untyped_defs = true
implicit_optional = true
disable_error_code = ["import-untyped"]
exclude = ["tests"]

[[tool.mypy.overrides]]
module = ["ldap.*"]
ignore_missing_imports = true

[tool.black]
line-length = 120
exclude = 'app/templates'