from __future__ import annotations

from datetime import datetime, timezone
from typing import TYPE_CHECKING

from app.config.db import tables as tbl
from app.module.calendar.model.CalendarInvite import CalendarInvite
from app.utils import errors as err
from app.utils.db.Condition import AndCondition, EqualCondition
from app.utils.exceptions import RequestException
from app.utils.logger.logger import logger_calendar

if TYPE_CHECKING:
    from app.manager.db.ClientSQL import ClientSQL


_ALL_COLS: tuple[str, ...] = tuple(col.name for col in tbl.ALL_CAL_INVITE_COL)

# id is generated by the module, so we insert everything including id
_INSERT_COLS: tuple[str, ...] = tuple(col.name for col in tbl.ALL_CAL_INVITE_COL)


class RepositoryCalendarInvite:
    """Handles all DB reads and writes for sogo_calendar_invites."""

    def __init__(self, db: ClientSQL) -> None:
        self._db = db

    @staticmethod
    def _row_to_invite(row: tuple) -> CalendarInvite:
        d = dict(zip(_ALL_COLS, row))
        return CalendarInvite(
            id=d["id"],
            calendar_key=d["calendar_key"],
            user_uid=d["user_uid"],
            invited_by=d["invited_by"],
            status=d["status"],
            share_level=d["share_level"],
            created_at=d["created_at"],
            updated_at=d["updated_at"],
        )

    def insert(self, invite: CalendarInvite) -> CalendarInvite:
        """Persist a new invite row."""
        now = datetime.now(timezone.utc)
        values = [[
            invite.id,
            invite.calendar_key,
            invite.user_uid,
            invite.invited_by,
            invite.status,
            invite.share_level,
            now,
            now,
        ]]
        try:
            inserted = self._db.insert_in_table(
                table_name=tbl.TABLE_CALENDAR_INVITE.name,
                column_tuple=_INSERT_COLS,
                values_tuple=values,
            )
        except Exception as exc:  # noqa: BLE001 - normalized below
            logger_calendar.error(
                "Unique violation inserting invite calendar_key=%s user=%s: %s",
                invite.calendar_key, invite.user_uid, exc,
            )
            raise RequestException(error=err.ERROR_CALENDAR_INVITE_ALREADY_EXISTS) from exc

        if inserted != 1:
            logger_calendar.error(
                "Calendar invite insert affected %s rows instead of 1 (calendar_key=%s, user=%s)",
                inserted, invite.calendar_key, invite.user_uid,
            )
            raise RequestException(error=err.ERROR_CALENDAR_INVITE_ALREADY_EXISTS)

        return invite

    def find_by_id(self, invite_id: str) -> CalendarInvite | None:
        """Return an invite by its id, or None."""
        condition = EqualCondition(tbl.COL_CAL_INVITE_ID.name, invite_id)
        rows = list(self._db.select_from_table(
            table_name=tbl.TABLE_CALENDAR_INVITE.name,
            column_tuple=_ALL_COLS,
            condition=condition,
            limit=1,
        ))
        return self._row_to_invite(rows[0]) if rows else None

    def find_by_calendar_and_user(self, calendar_key: str, user_uid: str) -> CalendarInvite | None:
        """Return the (latest) invite for a user on a calendar, or None."""
        condition = AndCondition(
            EqualCondition(tbl.COL_CAL_INVITE_CALENDAR_KEY.name, calendar_key),
            EqualCondition(tbl.COL_CAL_INVITE_USER_UID.name, user_uid),
        )
        rows = list(self._db.select_from_table(
            table_name=tbl.TABLE_CALENDAR_INVITE.name,
            column_tuple=_ALL_COLS,
            condition=condition,
            sort_by=tbl.COL_CAL_INVITE_CREATED_AT.name,
            limit=1,
        ))
        return self._row_to_invite(rows[0]) if rows else None

    def find_pending_for_user(self, user_uid: str) -> list[CalendarInvite]:
        """Return all pending invites for the given user."""
        condition = AndCondition(
            EqualCondition(tbl.COL_CAL_INVITE_USER_UID.name, user_uid),
            EqualCondition(tbl.COL_CAL_INVITE_STATUS.name, "pending"),
        )
        rows = self._db.select_from_table(
            table_name=tbl.TABLE_CALENDAR_INVITE.name,
            column_tuple=_ALL_COLS,
            condition=condition,
            sort_by=tbl.COL_CAL_INVITE_CREATED_AT.name,
        )
        return [self._row_to_invite(row) for row in rows]

    def find_by_calendar(self, calendar_key: str) -> list[CalendarInvite]:
        """Return all invites for a calendar."""
        condition = EqualCondition(tbl.COL_CAL_INVITE_CALENDAR_KEY.name, calendar_key)
        rows = self._db.select_from_table(
            table_name=tbl.TABLE_CALENDAR_INVITE.name,
            column_tuple=_ALL_COLS,
            condition=condition,
            sort_by=tbl.COL_CAL_INVITE_CREATED_AT.name,
        )
        return [self._row_to_invite(row) for row in rows]

    def update_status(self, invite_id: str, status: str) -> None:
        """Update the status of an invite row."""
        condition = EqualCondition(tbl.COL_CAL_INVITE_ID.name, invite_id)
        updated = self._db.update_in_table(
            table_name=tbl.TABLE_CALENDAR_INVITE.name,
            column_tuple=(tbl.COL_CAL_INVITE_STATUS.name, tbl.COL_CAL_INVITE_UPDATED_AT.name),
            # update_in_table takes ONE value per column (flat list), not a
            # row-nested list — [[...]] trips its column/value length check.
            values_list=[status, datetime.now(timezone.utc)],
            condition=condition,
        )
        if not updated:
            logger_calendar.error("Calendar invite %s not found on status update", invite_id)
            raise RequestException(error=err.ERROR_CALENDAR_INVITE_NOT_FOUND)

    def delete(self, invite_id: str) -> None:
        """Remove an invite row."""
        condition = EqualCondition(tbl.COL_CAL_INVITE_ID.name, invite_id)
        deleted = self._db.delete_row_in_table(
            table_name=tbl.TABLE_CALENDAR_INVITE.name,
            condition=condition,
            expected_row=1,
        )
        if deleted == 0:
            logger_calendar.error("Calendar invite %s not found on delete", invite_id)
            raise RequestException(error=err.ERROR_CALENDAR_INVITE_NOT_FOUND)
